version: '3.9'
services:
  project-service-db:
    image: mysql:8.0
    container_name: project-service-mysql
    environment:
      MYSQL_DATABASE: project_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3315:3306"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
          condition: on-failure
    restart: always
  user-service-db:
    image: mysql:8.0
    container_name: user-service-mysql
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3316:3306"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    restart: always
  shop-service-db:
    image: mysql:8.0
    container_name: shop-service-mysql
    environment:
      MYSQL_DATABASE: shop_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3317:3306"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    restart: always
  discovery:
    image: hobbymate/discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    restart: always
  gateway:
    image: hobbymate/gateway-service
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    links:
      - discovery
    restart: always
  projects:
    image: hobbymate/project-service-api
    container_name: project-service
    build:
      context: ./project-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 2
      restart_policy:
        condition: on-failure
    links:
      - discovery
      - project-service-db
    depends_on:
       - discovery
       - project-service-db
       - users
       - shop
    restart: always

  users:
    image: hobbymate/user-service-api
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    links:
      - discovery
      - user-service-db
    depends_on:
      - discovery
      - user-service-db
    restart: always
  shop:
    image: hobbymate/shop-service-api
    container_name: shop-service
    build:
      context: ./shop-service
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    links:
      - discovery
      - shop-service-db
    depends_on:
      - discovery
      - shop-service-db
    restart: always
  webapp:
    image: hobbymate/hobbymate-webapp
    container_name: hobbymate-webapp
    build:
      context: ./hobbymate-webapp
      dockerfile: Dockerfile
    ports:
      - "9797:9797"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - gateway
    restart: always
