spring:
  application:
    name: hobbymate-project-service
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery-service:8094}/eureka
ribbon:
  eureka:
    enabled: true
server:
  port: ${PORT:8090}