spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://project-service-mysql:3306/project_db?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8094/eureka