spring:
  application:
    name: discovery-service

server:
  port: ${PORT:8094}
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
