spring:
  application:
    name: gateway-service
  profiles:
    active: '@spring.profiles.active@'
  cloud:
    gateway:
      routes:
        - id: hobbymate-project-service
          uri: lb://HOBBYMATE-PROJECT-SERVICE
          predicates:
          - Path=/projects/**
        - id: hobbymate-user-service
          uri: lb://HOBBYMATE-USER-SERVICE
          predicates:
          - Path=/users/**
        - id: hobbymate-shop-service
          uri: lb://HOBBYMATE-SHOP-SERVICE
          predicates:
          - Path=/shop/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - HEAD
              - PUT
              - DELETE
              - OPTIONS
      httpclient:
        connect-timeout: 10000
        response-timeout: 60s
server:
  port: ${PORT:8095}
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery:8761}/eureka