spring:
  application:
    name: gateway-service
  profiles:
    active: '@spring.profiles.active@'
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/projects-api/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users-api/**
        - id: shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/shop-api/**
        - id: containerized-products
server:
  port: ${PORT:8095}
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery-service:8094}/eureka